#export TESTDB = "Proxmox_testdb"

export PERLIB = ".."

all:

check:
	./create_testdb.pl

#	init_testdb.pl		\
#	print_testdb.pl		\
#	test_config.pl		\
#	test_mimetype.pl	\
#	test_greylist.pl	\
#	test_proxy.pl		\
#	test_unpack.pl


CLEANFILES=*~ /proxytest_report.out test.cfg
